import { defineIndex } from 'twenty-sdk/define';

import {
  LOYALTY_ADJUSTMENT_REQUEST_IDEMPOTENCY_KEY_FIELD_UNIVERSAL_IDENTIFIER,
  LOYALTY_ADJUSTMENT_REQUEST_UNIQUE_IDEMPOTENCY_KEY_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
  LOYALTY_ADJUSTMENT_REQUEST_UNIQUE_IDEMPOTENCY_KEY_INDEX_UNIVERSAL_IDENTIFIER,
  LOYALTY_ADJUSTMENT_REQUEST_UNIVERSAL_IDENTIFIER,
} from 'src/objects/loyalty-adjustment-request.object';

export default defineIndex({
  universalIdentifier:
    LOYALTY_ADJUSTMENT_REQUEST_UNIQUE_IDEMPOTENCY_KEY_INDEX_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: LOYALTY_ADJUSTMENT_REQUEST_UNIVERSAL_IDENTIFIER,
  isUnique: true,
  fields: [
    {
      universalIdentifier:
        LOYALTY_ADJUSTMENT_REQUEST_UNIQUE_IDEMPOTENCY_KEY_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        LOYALTY_ADJUSTMENT_REQUEST_IDEMPOTENCY_KEY_FIELD_UNIVERSAL_IDENTIFIER,
    },
  ],
});
